version: '3.6'

services:
 api:
  build: .
  depends_on:
   - db
  environment:
   - POSTGRES_URL=db
  networks:
   - mynet
  ports:
   - 5000:5000
  volumes:
   - ./app:/app   
  restart: always

 db:
  environment:
   - POSTGRES_USER=seba
   - POSTGRES_PASSWORD=passwd
   - POSTGRES_DB=test
  image: postgres:latest
  networks:
  - mynet
  ports:
  - 5432:5432
  restart: always
  #volumes:
          #- ./src/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh

networks:
 mynet:
  driver: bridge